# Generated by Django 2.2.5 on 2019-09-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newscategory', models.CharField(max_length=200, verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Nachrichtenkategorie',
                'verbose_name_plural': 'Nachrichtenkategorien',
            },
        ),
        migrations.CreateModel(
            name='NewsLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200, verbose_name='Sprache')),
                ('code', models.CharField(max_length=5, verbose_name='Sprachcode')),
            ],
            options={
                'verbose_name': 'Sprache',
                'verbose_name_plural': 'Sprachen',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('enewsno', models.CharField(max_length=20, verbose_name='E-News Nummer')),
                ('pub_date', models.DateTimeField(verbose_name='Datum')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsLanguage')),
                ('newscategory', models.ManyToManyField(to='news.NewsCategory')),
            ],
            options={
                'verbose_name': 'Nachricht',
                'verbose_name_plural': 'Nachrichten',
            },
        ),
    ]
