# Generated by Django 3.0.5 on 2020-04-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-enewsno'], 'verbose_name': 'Nachricht', 'verbose_name_plural': 'Nachrichten'},
        ),
    ]
