# Generated by Django 3.0.5 on 2020-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200404_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscategory',
            old_name='newscategory',
            new_name='name',
        ),
    ]
