# Generated by Django 3.1.7 on 2021-03-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200404_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='wppostid',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newslanguage',
            name='wpcategory',
            field=models.IntegerField(null=True, unique=True, verbose_name='WordPress-Kategorie-ID'),
        ),
    ]
